# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'huishou' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for huishou
pod 'AFNetworking', '3.2.1'
pod 'MJRefresh'
pod 'IQKeyboardManager', '~> 5.0.7'
pod 'MJExtension'
pod "SVProgressHUD-0.8.1"
pod 'Masonry'
pod 'SDCycleScrollView', '~> 1.80'
pod 'TYPagerController'
pod 'AMap2DMap-NO-IDFA'
pod 'AMapSearch-NO-IDFA'
pod 'AMapLocation-NO-IDFA'
pod 'ReactiveObjC'
pod 'MBProgressHUD', '~> 1.1.0'

pod 'UMCCommon'
pod 'UMCCommonLog'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
pod 'UMCPush'
pod 'AlipaySDK-iOS'
pod 'WechatOpenSDK'
end
